# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('platform', models.IntegerField(choices=[(1, b'mobile version'), (2, b'iphone app'), (3, b'ipad app'), (4, b'android app'), (5, b'winphone app'), (6, b'win8 app'), (7, b'full version')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('has_mobile', models.BooleanField()),
                ('uid', models.IntegerField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='timestamp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.User'),
        ),
    ]
