# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='platform',
            new_name='last_seen_platform',
        ),
        migrations.RenameField(
            model_name='timestamp',
            old_name='time',
            new_name='last_seen_time',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='online',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestamp',
            name='online_mobile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
