# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20161020_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
