# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_timestamp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(default=b'00000000000000000000000000000000', max_length=32),
        ),
    ]
