# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_user_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracking',
            field=models.BooleanField(default=True),
        ),
    ]
